// Fake data for the skills/chat demo (src/app.html, src/app.js) — no
// backend, no real Research/vision calls. Its whole point is to exercise
// the real UI and the real overlay-drawing path with fixture data instead
// of live ones, so wiring up the actual thing later is a data-source swap,
// not a UI rewrite. Substeps render as fake overlay stages (highlight +
// step textbox) until a real on-screen callout exists. See
// docs/features/skills.md for the model this mirrors.
//
// Substep shape is deliberately the same shape a real pipeline would
// produce: `last_known_bbox` is exactly the {x0,y0,x1,y1,image_width,
// image_height,anchor} Box2D that locate_element already returns (see
// src-tauri/src/lib.rs) — this fixture just plays the role of "the
// vision/plan call already ran and here's its result", so the schematic
// renderer in sidebar.js doesn't know or care whether a box came from a
// live call or a fixture.
// image_width/image_height are the captured frame's own size; x0..y1 are
// fractions of it. `anchor` says whose frame that is — {kind:"region"}
// here (today's only real path: a free-drawn/full-screen capture, see
// ADR 0003) vs. {kind:"window",label} for a window-picked capture, which
// no live code produces yet (BL-005/ADR 0005). The schematic renders both
// identically today; `anchor` only matters once a real on-screen overlay
// needs to know what to re-anchor a stale box against.
//
// origin: "ai" (blue) — generated by the plan, lazily, when the step is
//   reached. origin: "user" (pink) — created only because the user asked
//   a follow-up question; carries `question` (what they asked) in
//   addition to `instruction_text` (the answer).

// The reference frame these fixture coordinates were authored against.
// This IS the "screen size parameter" that makes them scalable: every
// x0..y1 below is a pixel position on a notional 1920x1080 frame, and
// every consumer divides by these to get a 0..1 fraction before scaling to
// whatever it's actually drawing on — the in-panel schematic uses them for
// its aspect-ratio and percentage offsets (schematicHtml in sidebar.js),
// and the real on-screen overlay re-multiplies the fraction by the target
// window's *current* rect (overlay.js). So nothing here is tied to a
// 1920x1080 display; these two numbers are only the denominator.
//
// 1920x1080 specifically because it's the most common desktop resolution,
// so the fixture boxes land in plausible-looking places when the schematic
// draws them, and because a real locate_element result carries the actual
// captured frame's size in the same two fields — keeping the fixture in
// the same shape means swapping fixtures for live data changes nothing
// downstream.
const REF_W = 1920;
const REF_H = 1080;

function bbox(x0, y0, x1, y1) {
  return { x0, y0, x1, y1, image_width: REF_W, image_height: REF_H, anchor: { kind: "region" } };
}

// `createdAt` is what the chat list ranks by, newest first, both within a
// group and between groups (a group sorts by its own newest chat). Fixture
// dates are fixed rather than relative to "now" so the demo's ordering is
// the same every run; a real chat gets Date.now() when it's created.
export const SKILLS = [
  {
    id: "excel-chart",
    title: "Make a chart in Excel",
    goal: "How do I make a chart in Excel?",
    appName: "Excel",
    createdAt: "2026-08-27T14:05:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Select your data",
        generated: true,
        substeps: [
          {
            id: "s1-1",
            origin: "ai",
            target_description: "the range of cells containing your table, including headers",
            instruction_text: "Click and drag to select A1:C7 — make sure the header row is included.",
            action: "select",
            last_known_bbox: bbox(220, 260, 640, 560),
          },
          {
            id: "s1-2",
            origin: "ai",
            target_description: "the header row of your table",
            instruction_text: "Double check the first row has labels like “Month” and “Revenue” — the chart uses these as its legend.",
            action: "none",
            last_known_bbox: bbox(220, 260, 640, 292),
          },
        ],
      },
      {
        id: "s2",
        title: "Insert the chart",
        generated: true,
        substeps: [
          {
            id: "s2-1",
            origin: "ai",
            target_description: "the Insert tab in the ribbon",
            instruction_text: "Click the Insert tab at the top of the window.",
            action: "click",
            last_known_bbox: bbox(176, 84, 250, 118),
          },
          {
            id: "s2-2",
            origin: "user",
            question: "I don't have an Insert tab, where is it?",
            instruction_text: "It's in the ribbon at the very top, next to Home — if the ribbon is collapsed, click the small ⌃ arrow in the top-right corner first to expand it.",
            action: "none",
            last_known_bbox: bbox(1780, 20, 1860, 52),
          },
          {
            id: "s2-3",
            origin: "ai",
            target_description: "the Recommended Charts button in the Charts group",
            instruction_text: "Click Recommended Charts, then pick the bar chart Excel suggests.",
            action: "click",
            last_known_bbox: bbox(760, 90, 980, 150),
          },
        ],
      },
      {
        id: "s3",
        title: "Style your chart",
        generated: false,
        substeps: [],
      },
    ],
  },
  {
    // Deliberately named "Microsoft Excel" where the one above says
    // "Excel": the two are the same app under two of the names its
    // identity can arrive under (an X11 WM_CLASS vs. what the vision model
    // calls it, see identify_app.py), and grouping them together is the
    // case appGroupKey() in sidebar.js exists to handle.
    id: "excel-pivot",
    title: "Make a pivot table",
    goal: "How do I make a pivot table in Excel?",
    appName: "Microsoft Excel",
    createdAt: "2026-08-28T09:20:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Select the source data",
        generated: true,
        substeps: [
          {
            id: "s1-1",
            origin: "ai",
            target_description: "the range of cells to summarise, including headers",
            instruction_text: "Select A1:D40 — a pivot table needs the header row to name its fields.",
            action: "select",
            last_known_bbox: bbox(220, 260, 780, 700),
          },
        ],
      },
      {
        id: "s2",
        title: "Insert the pivot table",
        generated: false,
        substeps: [],
      },
      {
        id: "s3",
        title: "Choose rows, columns and values",
        generated: false,
        substeps: [],
      },
    ],
  },
  {
    id: "inkscape-blue-circle",
    title: "Create a blue circle in Inkscape",
    goal: "I want to create a circle and fill it with blue",
    appName: "Inkscape",
    createdAt: "2026-08-30T12:00:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Select the ellipse tool",
        generated: false,
        substeps: [],
      },
      {
        id: "s2",
        title: "Draw the circle",
        generated: false,
        substeps: [],
      },
      {
        id: "s3",
        title: "Fill it with blue",
        generated: false,
        substeps: [],
      },
    ],
  },
];

// Small pool of canned replies for substeps created live from the chat
// input during a demo — clearly a placeholder, not real generation.
const CANNED_REPLIES = [
  "Good question. Based on the current step, here's what I'd try: look for the same area highlighted in the previous instruction — it's usually still the fastest path.",
  "That can vary by version, but it's normally in the same ribbon tab we just highlighted. Try expanding the ribbon if you don't see it.",
  "You can usually get there with a right-click on the selection, too, if the button isn't visible.",
];

let replyIndex = 0;
export function nextCannedReply() {
  const reply = CANNED_REPLIES[replyIndex % CANNED_REPLIES.length];
  replyIndex += 1;
  return reply;
}
