// Fake data for the skills/chat demo (src/app.html, src/app.js) — no
// backend, no real Research/vision calls. Its whole point is to exercise
// the real UI and the real overlay-drawing path with fixture data instead
// of live ones, so wiring up the actual thing later is a data-source swap,
// not a UI rewrite. See docs/features/skills.md for the model this mirrors.
//
// Substep shape is deliberately the same shape a real pipeline would
// produce: `last_known_bbox` is exactly the {x0,y0,x1,y1,image_width,
// image_height,anchor} Box2D that locate_element already returns (see
// src-tauri/src/lib.rs) — this fixture just plays the role of "the
// vision/plan call already ran and here's its result", so the schematic
// renderer in sidebar.js doesn't know or care whether a box came from a
// live call or a fixture.
// image_width/image_height are the captured frame's own size; x0..y1 are
// fractions of it. `anchor` says whose frame that is — {kind:"region"}
// here (today's only real path: a free-drawn/full-screen capture, see
// ADR 0003) vs. {kind:"window",label} for a window-picked capture, which
// no live code produces yet (BL-005/ADR 0005). The schematic renders both
// identically today; `anchor` only matters once a real on-screen overlay
// needs to know what to re-anchor a stale box against.
//
// origin: "ai" (blue) — generated by the plan, lazily, when the step is
//   reached. origin: "user" (pink) — created only because the user asked
//   a follow-up question; carries `question` (what they asked) in
//   addition to `instruction_text` (the answer).

const REF_W = 1920;
const REF_H = 1080;

function bbox(x0, y0, x1, y1) {
  return { x0, y0, x1, y1, image_width: REF_W, image_height: REF_H, anchor: { kind: "region" } };
}

export const SKILLS = [
  {
    id: "excel-chart",
    title: "Make a chart in Excel",
    goal: "How do I make a chart in Excel?",
    steps: [
      {
        id: "s1",
        title: "Select your data",
        generated: true,
        substeps: [
          {
            id: "s1-1",
            origin: "ai",
            target_description: "the range of cells containing your table, including headers",
            instruction_text: "Click and drag to select A1:C7 — make sure the header row is included.",
            action: "select",
            last_known_bbox: bbox(220, 260, 640, 560),
          },
          {
            id: "s1-2",
            origin: "ai",
            target_description: "the header row of your table",
            instruction_text: "Double check the first row has labels like “Month” and “Revenue” — the chart uses these as its legend.",
            action: "none",
            last_known_bbox: bbox(220, 260, 640, 292),
          },
        ],
      },
      {
        id: "s2",
        title: "Insert the chart",
        generated: true,
        substeps: [
          {
            id: "s2-1",
            origin: "ai",
            target_description: "the Insert tab in the ribbon",
            instruction_text: "Click the Insert tab at the top of the window.",
            action: "click",
            last_known_bbox: bbox(176, 84, 250, 118),
          },
          {
            id: "s2-2",
            origin: "user",
            question: "I don't have an Insert tab, where is it?",
            instruction_text: "It's in the ribbon at the very top, next to Home — if the ribbon is collapsed, click the small ⌃ arrow in the top-right corner first to expand it.",
            action: "none",
            last_known_bbox: bbox(1780, 20, 1860, 52),
          },
          {
            id: "s2-3",
            origin: "ai",
            target_description: "the Recommended Charts button in the Charts group",
            instruction_text: "Click Recommended Charts, then pick the bar chart Excel suggests.",
            action: "click",
            last_known_bbox: bbox(760, 90, 980, 150),
          },
        ],
      },
      {
        id: "s3",
        title: "Style your chart",
        generated: false,
        substeps: [],
      },
    ],
  },
];

// Small pool of canned replies for substeps created live from the chat
// input during a demo — clearly a placeholder, not real generation.
const CANNED_REPLIES = [
  "Good question. Based on the current step, here's what I'd try: look for the same area highlighted in the previous instruction — it's usually still the fastest path.",
  "That can vary by version, but it's normally in the same ribbon tab we just highlighted. Try expanding the ribbon if you don't see it.",
  "You can usually get there with a right-click on the selection, too, if the button isn't visible.",
];

let replyIndex = 0;
export function nextCannedReply() {
  const reply = CANNED_REPLIES[replyIndex % CANNED_REPLIES.length];
  replyIndex += 1;
  return reply;
}
